### ISSUE TITLE
Adjustment of NPC behaviour

### ISSUE THREAD

**Issue by ghost** [EdoWahdana/pletokan-game#2]
NPC behaviour became not related to the algorithm when player reached a certain amount of distance to NPC, it was moving back and forth and freezing at the end. I think there might be wrong conditions on the algorithm for the NPC.

**Comment by EdoWahdana** [comment]
Yes, that is also what we found at the development phase, apparently that problem occurs because the condition of the algorithm is not relative to what the NPC is doing. We have fixed that problem, and that closed this issue.

Thank you for your input.
